// Comprehensive Placement Preparation Problem Set (100+ Problems)
// Organized by topics with difficulty levels for structured learning

const comprehensiveProblemSet = {
  recursion: {
    name: 'Recursion',
    description: 'Master recursion with fundamental and advanced problems',
    recommendedDays: 2,
    problems: [
      { sno: 1, title: 'Fibonacci Number', difficulty: 'easy', leetcodeId: '509', category: 'recursion', description: 'The Fibonacci numbers form a sequence where each number is the sum of the two preceding ones.', examples: [{ input: 'n = 2', output: '1' }, { input: 'n = 4', output: '3' }], constraints: ['0 <= n <= 30'], hints: ['Use recursion with memoization', 'Base cases: F(0)=0, F(1)=1'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 2, title: 'Factorial', difficulty: 'easy', leetcodeId: null, category: 'recursion', description: 'Calculate the factorial of a given number n.', examples: [{ input: 'n = 5', output: '120' }], constraints: ['0 <= n <= 12'], hints: ['n! = n * (n-1)!', 'Base case: 0! = 1'], companies: [], interviewFrequency: { faang: 5, service: 6, startup: 4 } },
      { sno: 3, title: 'Reverse String', difficulty: 'easy', leetcodeId: '344', category: 'recursion', description: 'Write a function that reverses a string using recursion.', examples: [{ input: 's = ["h","e","l","l","o"]', output: '["o","l","l","e","h"]' }], constraints: ['1 <= s.length <= 10^5'], hints: ['Swap first and last characters', 'Recurse on remaining substring'], companies: ['Apple', 'Microsoft'], interviewFrequency: { faang: 6, service: 7, startup: 5 } },
      { sno: 4, title: 'Sum of Digits', difficulty: 'easy', leetcodeId: null, category: 'recursion', description: 'Given an integer, return the sum of its digits using recursion.', examples: [{ input: 'n = 123', output: '6' }], constraints: ['n >= 0'], hints: ['n % 10 gives last digit', 'n / 10 removes last digit'], companies: [], interviewFrequency: { faang: 4, service: 5, startup: 4 } },
      { sno: 5, title: "Pascal's Triangle", difficulty: 'easy', leetcodeId: '118', category: 'recursion', description: 'Given an integer numRows, return the first numRows of Pascal\'s triangle.', examples: [{ input: 'numRows = 5', output: '[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]' }], constraints: ['1 <= numRows <= 30'], hints: ['Each number is sum of two above', 'Use previous row to build next'], companies: ['Amazon', 'Apple'], interviewFrequency: { faang: 6, service: 7, startup: 5 } },
      { sno: 6, title: 'Generate Parentheses', difficulty: 'medium', leetcodeId: '22', category: 'recursion', description: 'Given n pairs of parentheses, generate all combinations of well-formed parentheses.', examples: [{ input: 'n = 3', output: '["((()))","(()())","(())()","()(())","()()()"]' }], constraints: ['1 <= n <= 8'], hints: ['Track open and close counts', 'Add open if open < n', 'Add close if close < open'], companies: ['Google', 'Facebook', 'Amazon'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 7, title: 'Letter Combinations of Phone Number', difficulty: 'medium', leetcodeId: '17', category: 'recursion', description: 'Given a string containing digits from 2-9 inclusive, return all possible letter combinations.', examples: [{ input: 'digits = "23"', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' }], constraints: ['0 <= digits.length <= 4'], hints: ['Use mapping of digit to letters', 'Backtrack through each digit'], companies: ['Amazon', 'Google', 'Uber'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 8, title: 'Pow(x, n)', difficulty: 'medium', leetcodeId: '50', category: 'recursion', description: 'Implement pow(x, n), which calculates x raised to the power n.', examples: [{ input: 'x = 2.00000, n = 10', output: '1024.00000' }], constraints: ['-100.0 < x < 100.0', '-2^31 <= n <= 2^31-1'], hints: ['Handle negative n', 'Use fast exponentiation'], companies: ['Facebook', 'LinkedIn'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 9, title: 'Count Good Numbers', difficulty: 'medium', leetcodeId: '1922', category: 'recursion', description: 'A digit string is good if digits at even indices are even and digits at odd indices are prime. Return count of good digit strings of length n.', examples: [{ input: 'n = 1', output: '5' }, { input: 'n = 4', output: '400' }], constraints: ['1 <= n <= 10^15'], hints: ['Even positions: 0,2,4,6,8 (5 choices)', 'Odd positions: 2,3,5,7 (4 choices)', 'Use fast power'], companies: ['Amazon'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 10, title: 'Tower of Hanoi', difficulty: 'medium', leetcodeId: null, category: 'recursion', description: 'Solve Tower of Hanoi puzzle. Move n disks from source rod to destination rod using auxiliary rod.', examples: [{ input: 'n = 2', output: 'Move disk 1 from A to B, Move disk 2 from A to C, Move disk 1 from B to C' }], constraints: ['1 <= n <= 20'], hints: ['Move n-1 disks to auxiliary', 'Move nth disk to destination', 'Move n-1 disks to destination'], companies: ['Microsoft', 'Adobe'], interviewFrequency: { faang: 7, service: 8, startup: 6 } },
      { sno: 11, title: 'All Possible Full Binary Trees', difficulty: 'medium', leetcodeId: '894', category: 'recursion', description: 'Given an integer n, return a list of all possible full binary trees with n nodes.', examples: [{ input: 'n = 7', output: '[[0,0,0,null,null,0,0,null,null,0,0],...]' }], constraints: ['1 <= n <= 20', 'n is odd'], hints: ['Root + left and right subtrees', 'Both subtrees must be full', 'Use memoization'], companies: ['Google'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 12, title: 'K-th Symbol in Grammar', difficulty: 'medium', leetcodeId: '779', category: 'recursion', description: 'In a grammar, row 1 is 0. For row n, append inverted row n-1. Find k-th symbol in row n.', examples: [{ input: 'n = 1, k = 1', output: '0' }, { input: 'n = 2, k = 1', output: '0' }, { input: 'n = 2, k = 2', output: '1' }], constraints: ['1 <= n <= 30', '1 <= k <= 2^(n-1)'], hints: ['First half = row n-1', 'Second half = inverse of row n-1', 'Check which half k is in'], companies: ['Google', 'Amazon'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 13, title: 'Beautiful Arrangement', difficulty: 'hard', leetcodeId: '526', category: 'recursion', description: 'Count permutations of [1,n] where at position i, either perm[i] is divisible by i or i is divisible by perm[i].', examples: [{ input: 'n = 2', output: '2' }, { input: 'n = 3', output: '3' }], constraints: ['1 <= n <= 15'], hints: ['Use backtracking', 'Check divisibility condition', 'Try all permutations'], companies: ['Google'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 14, title: 'Predict the Winner', difficulty: 'hard', leetcodeId: '486', category: 'recursion', description: 'Two players take turns picking numbers from either end of array. Predict if Player 1 can win.', examples: [{ input: 'nums = [1,5,2]', output: 'false' }, { input: 'nums = [1,5,233,7]', output: 'true' }], constraints: ['1 <= nums.length <= 20', '0 <= nums[i] <= 10^7'], hints: ['Minimax approach', 'Player 1 maximizes, Player 2 minimizes', 'Use DP to optimize'], companies: ['Google', 'Amazon'], interviewFrequency: { faang: 8, service: 7, startup: 6 } },
      { sno: 15, title: 'Parse Lisp Expression', difficulty: 'hard', leetcodeId: '736', category: 'recursion', description: 'Evaluate a Lisp expression with let, add, mult, and variable assignments.', examples: [{ input: '"(add 1 2)"', output: '3' }, { input: '"(let a 1 b 2 (add a b))"', output: '3' }], constraints: ['Expression length <= 2000'], hints: ['Parse recursively', 'Handle nested expressions', 'Manage scope for variables'], companies: ['Facebook'], interviewFrequency: { faang: 6, service: 5, startup: 4 } }
    ]
  },
  
  hashing: {
    name: 'Hashing (Advanced)',
    description: 'Master hash maps and sets for efficient lookups',
    recommendedDays: 2,
    problems: [
      { sno: 1, title: 'Two Sum', difficulty: 'easy', leetcodeId: '1', category: 'hash_table', description: 'Return indices of two numbers that add up to target.', examples: [{ input: 'nums = [2,7,11,15], target = 9', output: '[0,1]' }], constraints: ['2 <= nums.length <= 10^4'], hints: ['Use hash map to store complement', 'Check if complement exists'], companies: ['Amazon', 'Google', 'Facebook', 'Apple', 'Microsoft'], interviewFrequency: { faang: 10, service: 9, startup: 8 } },
      { sno: 2, title: 'Contains Duplicate', difficulty: 'easy', leetcodeId: '217', category: 'hash_table', description: 'Return true if any value appears at least twice in array.', examples: [{ input: 'nums = [1,2,3,1]', output: 'true' }], constraints: ['1 <= nums.length <= 10^5'], hints: ['Use hash set', 'Check if element already in set'], companies: ['Amazon', 'Apple'], interviewFrequency: { faang: 7, service: 8, startup: 6 } },
      { sno: 3, title: 'Valid Anagram', difficulty: 'easy', leetcodeId: '242', category: 'hash_table', description: 'Return true if t is an anagram of s.', examples: [{ input: 's = "anagram", t = "nagaram"', output: 'true' }], constraints: ['1 <= s.length, t.length <= 5*10^4'], hints: ['Use character frequency map', 'Compare counts'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 8, service: 9, startup: 7 } },
      { sno: 4, title: 'Intersection of Two Arrays', difficulty: 'easy', leetcodeId: '349', category: 'hash_table', description: 'Return unique elements common to both arrays.', examples: [{ input: 'nums1 = [1,2,2,1], nums2 = [2,2]', output: '[2]' }], constraints: ['1 <= nums1.length, nums2.length <= 1000'], hints: ['Use set for one array', 'Check presence in set'], companies: ['Facebook', 'Microsoft'], interviewFrequency: { faang: 6, service: 7, startup: 6 } },
      { sno: 5, title: 'First Unique Character in String', difficulty: 'easy', leetcodeId: '387', category: 'hash_table', description: 'Find first non-repeating character and return its index.', examples: [{ input: 's = "leetcode"', output: '0' }, { input: 's = "loveleetcode"', output: '2' }], constraints: ['1 <= s.length <= 10^5'], hints: ['Count character frequencies', 'Find first with count 1'], companies: ['Amazon', 'Microsoft'], interviewFrequency: { faang: 7, service: 8, startup: 6 } },
      { sno: 6, title: 'Group Anagrams', difficulty: 'medium', leetcodeId: '49', category: 'hash_table', description: 'Group strings that are anagrams of each other.', examples: [{ input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }], constraints: ['1 <= strs.length <= 10^4'], hints: ['Use sorted string as key', 'Group by character count'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 7, title: 'Longest Consecutive Sequence', difficulty: 'medium', leetcodeId: '128', category: 'hash_table', description: 'Find length of longest consecutive elements sequence.', examples: [{ input: 'nums = [100,4,200,1,3,2]', output: '4' }], constraints: ['0 <= nums.length <= 10^5'], hints: ['Use hash set', 'Check if num-1 exists', 'Count consecutive'], companies: ['Google', 'Facebook'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 8, title: 'Subarray Sum Equals K', difficulty: 'medium', leetcodeId: '560', category: 'hash_table', description: 'Count number of subarrays with sum equal to k.', examples: [{ input: 'nums = [1,1,1], k = 2', output: '2' }], constraints: ['1 <= nums.length <= 2*10^4'], hints: ['Use prefix sum hash map', 'Count sum - k occurrences'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 9, title: '4Sum', difficulty: 'medium', leetcodeId: '18', category: 'hash_table', description: 'Find all unique quadruplets that sum to target.', examples: [{ input: 'nums = [1,0,-1,0,-2,2], target = 0', output: '[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]' }], constraints: ['1 <= nums.length <= 200'], hints: ['Sort array', 'Use two nested loops + two pointers'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 10, title: 'Longest Substring Without Repeating Characters', difficulty: 'medium', leetcodeId: '3', category: 'hash_table', description: 'Find length of longest substring without repeating characters.', examples: [{ input: 's = "abcabcbb"', output: '3' }], constraints: ['0 <= s.length <= 5*10^4'], hints: ['Sliding window + hash set', 'Track character indices'], companies: ['Amazon', 'Facebook', 'Google', 'Adobe'], interviewFrequency: { faang: 10, service: 9, startup: 8 } },
      { sno: 11, title: 'Find All Anagrams in String', difficulty: 'medium', leetcodeId: '438', category: 'hash_table', description: 'Find all start indices of p\'s anagrams in s.', examples: [{ input: 's = "cbaebabacd", p = "abc"', output: '[0,6]' }], constraints: ['1 <= s.length, p.length <= 3*10^4'], hints: ['Use character count array', 'Sliding window comparison'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 12, title: 'Substring with Concatenation of All Words', difficulty: 'hard', leetcodeId: '30', category: 'hash_table', description: 'Find all starting indices of substring that is concatenation of all words.', examples: [{ input: 's = "barfoothefoobarman", words = ["foo","bar"]', output: '[0,9]' }], constraints: ['1 <= s.length <= 10^4', '1 <= words.length <= 5000'], hints: ['Use word frequency map', 'Sliding window of fixed size'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 13, title: 'Max Points on a Line', difficulty: 'hard', leetcodeId: '149', category: 'hash_table', description: 'Return maximum number of points that lie on the same straight line.', examples: [{ input: 'points = [[1,1],[2,2],[3,3]]', output: '3' }], constraints: ['1 <= points.length <= 300'], hints: ['Calculate slope for each pair', 'Use hash map to count slopes'], companies: ['Google', 'Amazon'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 14, title: 'Count of Range Sum', difficulty: 'hard', leetcodeId: '327', category: 'hash_table', description: 'Count range sums that lie in [lower, upper] inclusive.', examples: [{ input: 'nums = [-2,5,-1], lower = -2, upper = 2', output: '3' }], constraints: ['1 <= nums.length <= 10^5'], hints: ['Use prefix sum + BST', 'Merge sort approach'], companies: ['Google'], interviewFrequency: { faang: 5, service: 4, startup: 3 } },
      { sno: 15, title: 'Subarrays with K Different Integers', difficulty: 'hard', leetcodeId: '992', category: 'hash_table', description: 'Return number of subarrays with exactly k different integers.', examples: [{ input: 'nums = [1,2,1,2,3], k = 2', output: '7' }], constraints: ['1 <= nums.length <= 2*10^4'], hints: ['At most K - At most (K-1)', 'Sliding window with hash map'], companies: ['Google', 'Amazon'], interviewFrequency: { faang: 7, service: 6, startup: 5 } }
    ]
  },

  twoPointers: {
    name: 'Two Pointers (Advanced)',
    description: 'Master two pointer technique for array and string problems',
    recommendedDays: 1,
    problems: [
      { sno: 1, title: 'Valid Palindrome', difficulty: 'easy', leetcodeId: '125', category: 'strings', description: 'Determine if string is palindrome, considering only alphanumeric chars and ignoring cases.', examples: [{ input: 's = "A man, a plan, a canal: Panama"', output: 'true' }], constraints: ['1 <= s.length <= 2*10^5'], hints: ['Use two pointers from ends', 'Skip non-alphanumeric'], companies: ['Facebook', 'Microsoft'], interviewFrequency: { faang: 7, service: 8, startup: 6 } },
      { sno: 2, title: 'Move Zeroes', difficulty: 'easy', leetcodeId: '283', category: 'arrays', description: 'Move all zeros to end while maintaining relative order of non-zero elements.', examples: [{ input: 'nums = [0,1,0,3,12]', output: '[1,3,12,0,0]' }], constraints: ['1 <= nums.length <= 10^4'], hints: ['Two pointers: one for non-zero', 'Swap non-zero forward'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 8, startup: 6 } },
      { sno: 3, title: 'Remove Duplicates from Sorted Array', difficulty: 'easy', leetcodeId: '26', category: 'arrays', description: 'Remove duplicates in-place such that each unique element appears only once.', examples: [{ input: 'nums = [1,1,2]', output: '2, nums = [1,2,_]' }], constraints: ['0 <= nums.length <= 3*10^4'], hints: ['Two pointers', 'Slow pointer for unique'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 8, service: 9, startup: 7 } },
      { sno: 4, title: 'Squares of Sorted Array', difficulty: 'easy', leetcodeId: '977', category: 'arrays', description: 'Return array of squares of each number sorted in non-decreasing order.', examples: [{ input: 'nums = [-4,-1,0,3,10]', output: '[0,1,9,16,100]' }], constraints: ['1 <= nums.length <= 10^4'], hints: ['Two pointers from ends', 'Larger square goes to end'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 8, startup: 6 } },
      { sno: 5, title: 'Merge Sorted Array', difficulty: 'easy', leetcodeId: '88', category: 'arrays', description: 'Merge two sorted arrays into one sorted array.', examples: [{ input: 'nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3', output: '[1,2,2,3,5,6]' }], constraints: ['nums1.length == m + n'], hints: ['Start from end', 'Compare and place larger at end'], companies: ['Facebook', 'Microsoft'], interviewFrequency: { faang: 8, service: 9, startup: 7 } },
      { sno: 6, title: '3Sum', difficulty: 'medium', leetcodeId: '15', category: 'arrays', description: 'Find all unique triplets in array which gives sum of zero.', examples: [{ input: 'nums = [-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]' }], constraints: ['0 <= nums.length <= 5000'], hints: ['Sort array', 'Fix one, use two pointers for rest'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 7, title: 'Container With Most Water', difficulty: 'medium', leetcodeId: '11', category: 'arrays', description: 'Find two lines that together with x-axis form a container that contains most water.', examples: [{ input: 'height = [1,8,6,2,5,4,8,3,7]', output: '49' }], constraints: ['n == height.length', '2 <= n <= 10^5'], hints: ['Two pointers from ends', 'Move pointer with smaller height'], companies: ['Amazon', 'Google', 'Facebook'], interviewFrequency: { faang: 9, service: 8, startup: 8 } },
      { sno: 8, title: 'Sort Colors', difficulty: 'medium', leetcodeId: '75', category: 'arrays', description: 'Sort array of 0, 1, 2 in-place (Dutch National Flag problem).', examples: [{ input: 'nums = [2,0,2,1,1,0]', output: '[0,0,1,1,2,2]' }], constraints: ['n == nums.length', '1 <= n <= 300'], hints: ['Three pointers', '0 on left, 2 on right'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 9, title: 'Trapping Rain Water', difficulty: 'medium', leetcodeId: '42', category: 'arrays', description: 'Compute how much water it can trap after raining.', examples: [{ input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }], constraints: ['n == height.length', '1 <= n <= 2*10^4'], hints: ['Two pointers', 'Track left and right max'], companies: ['Amazon', 'Google', 'Facebook'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 10, title: 'Remove Duplicates from Sorted Array II', difficulty: 'medium', leetcodeId: '80', category: 'arrays', description: 'Remove duplicates such that duplicates appear at most twice.', examples: [{ input: 'nums = [1,1,1,2,2,3]', output: '5, nums = [1,1,2,2,3,_]' }], constraints: ['1 <= nums.length <= 3*10^4'], hints: ['Count occurrences', 'Allow at most 2'], companies: ['Facebook'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 11, title: '3Sum Closest', difficulty: 'medium', leetcodeId: '16', category: 'arrays', description: 'Find sum of three integers in array closest to target.', examples: [{ input: 'nums = [-1,2,1,-4], target = 1', output: '2' }], constraints: ['3 <= nums.length <= 500'], hints: ['Sort array', 'Two pointers for closest sum'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 12, title: 'Minimum Window Substring', difficulty: 'hard', leetcodeId: '76', category: 'strings', description: 'Return minimum window substring containing all characters of t.', examples: [{ input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"' }], constraints: ['m == s.length', 'n == t.length', '1 <= m, n <= 10^5'], hints: ['Sliding window with hash map', 'Expand and contract'], companies: ['Facebook', 'Amazon', 'Google'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 13, title: 'Minimum Window Subsequence', difficulty: 'hard', leetcodeId: '727', category: 'strings', description: 'Return minimum contiguous substring of S that has subsequence T.', examples: [{ input: 'S = "abcdebdde", T = "bde"', output: '"bcde"' }], constraints: ['1 <= S.length <= 2000', '1 <= T.length <= 100'], hints: ['Two pointers', 'Find valid windows'], companies: ['Google'], interviewFrequency: { faang: 5, service: 4, startup: 3 } },
      { sno: 14, title: 'Trapping Rain Water II', difficulty: 'hard', leetcodeId: '407', category: 'arrays', description: 'Given m x n integer matrix heightMap, return volume of trapped rain water.', examples: [{ input: 'heightMap = [[1,4,3,1,3,2],[3,2,1,3,2,4],[2,3,3,2,3,1]]', output: '4' }], constraints: ['m == heightMap.length', 'n == heightMap[i].length'], hints: ['Use priority queue (min heap)', 'Start from boundary'], companies: ['Google', 'Amazon'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 15, title: 'Substring with Concatenation of All Words', difficulty: 'hard', leetcodeId: '30', category: 'strings', description: 'Find all starting indices of substring(s) in s that is a concatenation of each word in words.', examples: [{ input: 's = "barfoothefoobarman", words = ["foo","bar"]', output: '[0,9]' }], constraints: ['1 <= s.length <= 10^4'], hints: ['Hash map for word frequencies', 'Sliding window'], companies: ['Facebook'], interviewFrequency: { faang: 7, service: 6, startup: 5 } }
    ]
  },

  backtracking: {
    name: 'Backtracking',
    description: 'Master backtracking for combinatorial and constraint satisfaction problems',
    recommendedDays: 2,
    problems: [
      { sno: 1, title: 'Letter Case Permutation', difficulty: 'easy', leetcodeId: '784', category: 'backtracking', description: 'Return all possible strings we could create by changing case of letters.', examples: [{ input: 's = "a1b2"', output: '["a1b2","a1B2","A1b2","A1B2"]' }], constraints: ['1 <= s.length <= 12'], hints: ['For each letter, try both cases', 'Use recursion'], companies: ['Facebook'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 2, title: 'Binary Watch', difficulty: 'easy', leetcodeId: '401', category: 'backtracking', description: 'Return all possible times a binary watch could represent given turned on LEDs.', examples: [{ input: 'turnedOn = 1', output: '["0:01","0:02","0:04","0:08","0:16","0:32","1:00","2:00","4:00","8:00"]' }], constraints: ['0 <= turnedOn <= 10'], hints: ['Count bits in hours and minutes', 'Backtrack through possibilities'], companies: ['Google'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 3, title: 'Subsets', difficulty: 'easy', leetcodeId: '78', category: 'backtracking', description: 'Return all possible subsets (the power set).', examples: [{ input: 'nums = [1,2,3]', output: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]' }], constraints: ['1 <= nums.length <= 10'], hints: ['Include or exclude each element', 'Recursive approach'], companies: ['Facebook', 'Amazon', 'Google'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 4, title: 'Combination Sum III', difficulty: 'easy', leetcodeId: '216', category: 'backtracking', description: 'Find all valid combinations of k numbers that sum to n using 1-9 exactly once.', examples: [{ input: 'k = 3, n = 7', output: '[[1,2,4]]' }], constraints: ['2 <= k <= 9', '1 <= n <= 60'], hints: ['Backtrack from 1 to 9', 'Try each number once'], companies: ['Microsoft'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 5, title: 'Path Sum II', difficulty: 'easy', leetcodeId: '113', category: 'backtracking', description: 'Find all root-to-leaf paths where each path sum equals targetSum.', examples: [{ input: 'root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22', output: '[[5,4,11,2],[5,8,4,5]]' }], constraints: ['Number of nodes <= 5000'], hints: ['DFS with path tracking', 'Backtrack by removing last element'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 6, title: 'Combination Sum', difficulty: 'medium', leetcodeId: '39', category: 'backtracking', description: 'Find all unique combinations where candidate numbers sum to target.', examples: [{ input: 'candidates = [2,3,6,7], target = 7', output: '[[2,2,3],[7]]' }], constraints: ['1 <= candidates.length <= 30'], hints: ['Sort candidates', 'Backtrack with index to avoid duplicates'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 7, title: 'Combination Sum II', difficulty: 'medium', leetcodeId: '40', category: 'backtracking', description: 'Each number in candidates may only be used once.', examples: [{ input: 'candidates = [10,1,2,7,6,1,5], target = 8', output: '[[1,1,6],[1,2,5],[1,7],[2,6]]' }], constraints: ['1 <= candidates.length <= 100'], hints: ['Sort and skip duplicates', 'Use each number once'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 8, title: 'Permutations', difficulty: 'medium', leetcodeId: '46', category: 'backtracking', description: 'Return all possible permutations of nums.', examples: [{ input: 'nums = [1,2,3]', output: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' }], constraints: ['1 <= nums.length <= 6'], hints: ['Swap and recurse', 'Track used elements'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 9, title: 'Permutations II', difficulty: 'medium', leetcodeId: '47', category: 'backtracking', description: 'Return all unique permutations (contains duplicates).', examples: [{ input: 'nums = [1,1,2]', output: '[[1,1,2],[1,2,1],[2,1,1]]' }], constraints: ['1 <= nums.length <= 8'], hints: ['Sort first', 'Skip duplicates'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 10, title: 'Subsets II', difficulty: 'medium', leetcodeId: '90', category: 'backtracking', description: 'Return all subsets (contains duplicates).', examples: [{ input: 'nums = [1,2,2]', output: '[[],[1],[1,2],[1,2,2],[2],[2,2]]' }], constraints: ['1 <= nums.length <= 10'], hints: ['Sort first', 'Skip duplicates'], companies: ['Facebook'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 11, title: 'Palindrome Partitioning', difficulty: 'medium', leetcodeId: '131', category: 'backtracking', description: 'Partition s such that every substring is a palindrome.', examples: [{ input: 's = "aab"', output: '[["a","a","b"],["aa","b"]]' }], constraints: ['1 <= s.length <= 16'], hints: ['Check palindrome', 'Backtrack through partitions'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 12, title: 'Restore IP Addresses', difficulty: 'medium', leetcodeId: '93', category: 'backtracking', description: 'Return all possible valid IP address combinations.', examples: [{ input: 's = "25525511135"', output: '["255.255.11.135","255.255.111.35"]' }], constraints: ['1 <= s.length <= 12'], hints: ['Try 1-3 digit segments', 'Validate each segment'], companies: ['Facebook'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 13, title: 'N-Queens', difficulty: 'hard', leetcodeId: '51', category: 'backtracking', description: 'Return all distinct solutions to n-queens puzzle.', examples: [{ input: 'n = 4', output: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]' }], constraints: ['1 <= n <= 9'], hints: ['Place queen row by row', 'Check columns and diagonals'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 8, service: 7, startup: 6 } },
      { sno: 14, title: 'Sudoku Solver', difficulty: 'hard', leetcodeId: '37', category: 'backtracking', description: 'Fill empty cells solving sudoku puzzle.', examples: [{ input: 'board = [["5","3",".",".","7",".",".",".","."],...]', output: 'solved board' }], constraints: ['board.length == 9'], hints: ['Find empty cell', 'Try digits 1-9', 'Check validity'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 15, title: 'Word Break II', difficulty: 'hard', leetcodeId: '140', category: 'backtracking', description: 'Return all possible sentences formed by concatenating dictionary words.', examples: [{ input: 's = "catsanddog", wordDict = ["cat","cats","and","sand","dog"]', output: '["cats and dog","cat sand dog"]' }], constraints: ['1 <= s.length <= 20', '1 <= wordDict.length <= 1000'], hints: ['Backtrack with memoization', 'Try each word in dictionary'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 6, startup: 5 } }
    ]
  },

  dynamicProgramming: {
    name: 'Dynamic Programming',
    description: 'Master DP for optimization and counting problems',
    recommendedDays: 3,
    problems: [
      { sno: 1, title: 'House Robber', difficulty: 'easy', leetcodeId: '198', category: 'dynamic_programming', description: 'Maximize amount of money robbed without alerting police (adjacent houses).', examples: [{ input: 'nums = [1,2,3,1]', output: '4' }], constraints: ['1 <= nums.length <= 100'], hints: ['dp[i] = max(dp[i-1], dp[i-2] + nums[i])', 'Choose to rob or skip'], companies: ['Amazon', 'Google', 'Apple'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 2, title: 'Best Time to Buy and Sell Stock', difficulty: 'easy', leetcodeId: '121', category: 'dynamic_programming', description: 'Find maximum profit with at most one transaction.', examples: [{ input: 'prices = [7,1,5,3,6,4]', output: '5' }], constraints: ['1 <= prices.length <= 10^5'], hints: ['Track minimum price', 'Calculate max profit at each step'], companies: ['Amazon', 'Facebook', 'Google', 'Bloomberg'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 3, title: 'Climbing Stairs', difficulty: 'easy', leetcodeId: '70', category: 'dynamic_programming', description: 'Count distinct ways to climb to top taking 1 or 2 steps.', examples: [{ input: 'n = 2', output: '2' }, { input: 'n = 3', output: '3' }], constraints: ['1 <= n <= 45'], hints: ['dp[i] = dp[i-1] + dp[i-2]', 'Fibonacci pattern'], companies: ['Amazon', 'Google', 'Adobe', 'Microsoft'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 4, title: 'Min Cost Climbing Stairs', difficulty: 'easy', leetcodeId: '746', category: 'dynamic_programming', description: 'Find minimum cost to reach top where you can climb 1 or 2 steps.', examples: [{ input: 'cost = [10,15,20]', output: '15' }], constraints: ['2 <= cost.length <= 1000'], hints: ['dp[i] = cost[i] + min(dp[i+1], dp[i+2])', 'Work backwards'], companies: ['Amazon', 'Apple'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 5, title: 'Divisor Game', difficulty: 'easy', leetcodeId: '1025', category: 'dynamic_programming', description: 'Alice and Bob play game with number N. Return true if Alice wins.', examples: [{ input: 'N = 2', output: 'true' }, { input: 'N = 3', output: 'false' }], constraints: ['1 <= N <= 1000'], hints: ['dp[i] = any(not dp[i-x] for all divisors x)', 'Pattern: Alice wins on even'], companies: ['Google'], interviewFrequency: { faang: 5, service: 5, startup: 4 } },
      { sno: 6, title: 'Coin Change', difficulty: 'medium', leetcodeId: '322', category: 'dynamic_programming', description: 'Find fewest coins needed to make up amount.', examples: [{ input: 'coins = [1,2,5], amount = 11', output: '3' }], constraints: ['1 <= coins.length <= 12'], hints: ['dp[i] = min coins for amount i', 'Try each coin'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 7, title: 'Longest Increasing Subsequence', difficulty: 'medium', leetcodeId: '300', category: 'dynamic_programming', description: 'Return length of longest strictly increasing subsequence.', examples: [{ input: 'nums = [10,9,2,5,3,7,101,18]', output: '4' }], constraints: ['1 <= nums.length <= 2500'], hints: ['dp[i] = LIS ending at i', 'Binary search optimization possible'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 8, title: 'Longest Common Subsequence', difficulty: 'medium', leetcodeId: '1143', category: 'dynamic_programming', description: 'Return length of longest common subsequence of text1 and text2.', examples: [{ input: 'text1 = "abcde", text2 = "ace"', output: '3' }], constraints: ['1 <= text1.length, text2.length <= 1000'], hints: ['dp[i][j] = LCS of text1[0..i] and text2[0..j]', 'Match or skip'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 9, title: 'Unique Paths', difficulty: 'medium', leetcodeId: '62', category: 'dynamic_programming', description: 'Count unique paths from top-left to bottom-right moving only down or right.', examples: [{ input: 'm = 3, n = 7', output: '28' }], constraints: ['1 <= m, n <= 100'], hints: ['dp[i][j] = paths to reach (i,j)', 'dp[i][j] = dp[i-1][j] + dp[i][j-1]'], companies: ['Amazon', 'Google', 'Facebook'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 10, title: 'Edit Distance', difficulty: 'medium', leetcodeId: '72', category: 'dynamic_programming', description: 'Return minimum number of operations to convert word1 to word2.', examples: [{ input: 'word1 = "horse", word2 = "ros"', output: '3' }], constraints: ['0 <= word1.length, word2.length <= 500'], hints: ['dp[i][j] = edit distance', 'Insert, delete, replace'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 11, title: 'Partition Equal Subset Sum', difficulty: 'medium', leetcodeId: '416', category: 'dynamic_programming', description: 'Determine if array can be partitioned into two subsets with equal sum.', examples: [{ input: 'nums = [1,5,11,5]', output: 'true' }], constraints: ['1 <= nums.length <= 200'], hints: ['Subset sum problem', 'dp[j] = can make sum j'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 12, title: 'Target Sum', difficulty: 'medium', leetcodeId: '494', category: 'dynamic_programming', description: 'Find number of ways to assign + or - to make sum equal to target.', examples: [{ input: 'nums = [1,1,1,1,1], target = 3', output: '5' }], constraints: ['1 <= nums.length <= 20'], hints: ['Transform to subset sum', 'sum(P) - sum(N) = target'], companies: ['Facebook', 'Google'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 13, title: 'Best Time to Buy and Sell Stock IV', difficulty: 'hard', leetcodeId: '188', category: 'dynamic_programming', description: 'Find maximum profit with at most k transactions.', examples: [{ input: 'k = 2, prices = [2,4,1]', output: '2' }], constraints: ['0 <= k <= 100', '1 <= prices.length <= 1000'], hints: ['dp[t][i] = max profit with t transactions up to day i', 'Two states: hold or not hold'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 14, title: 'Burst Balloons', difficulty: 'hard', leetcodeId: '312', category: 'dynamic_programming', description: 'Return maximum coins by bursting balloons wisely.', examples: [{ input: 'nums = [3,1,5,8]', output: '167' }], constraints: ['n == nums.length', '1 <= n <= 500'], hints: ['dp[i][j] = max coins for bursting balloons between i and j', 'Try each as last to burst'], companies: ['Facebook', 'Google'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 15, title: 'Regular Expression Matching', difficulty: 'hard', leetcodeId: '10', category: 'dynamic_programming', description: 'Support . and * in pattern matching.', examples: [{ input: 's = "aa", p = "a"', output: 'false' }, { input: 's = "aa", p = "a*"', output: 'true' }], constraints: ['1 <= s.length <= 20', '1 <= p.length <= 30'], hints: ['dp[i][j] = first i chars of s match first j of p', 'Handle * specially'], companies: ['Facebook', 'Google', 'Amazon'], interviewFrequency: { faang: 8, service: 7, startup: 6 } }
    ]
  },

  greedy: {
    name: 'Greedy Algorithms',
    description: 'Master greedy approach for optimization problems',
    recommendedDays: 1,
    problems: [
      { sno: 1, title: 'Assign Cookies', difficulty: 'easy', leetcodeId: '455', category: 'greedy', description: 'Maximize number of content children with cookies.', examples: [{ input: 'g = [1,2,3], s = [1,1]', output: '1' }], constraints: ['1 <= g.length, s.length <= 3*10^4'], hints: ['Sort both arrays', 'Give smallest sufficient cookie'], companies: ['Google'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 2, title: 'Lemonade Change', difficulty: 'easy', leetcodeId: '860', category: 'greedy', description: 'Determine if you can provide correct change for every customer.', examples: [{ input: 'bills = [5,5,5,10,20]', output: 'true' }], constraints: ['1 <= bills.length <= 10^5'], hints: ['Track count of 5s and 10s', 'Give change greedily'], companies: ['Amazon'], interviewFrequency: { faang: 6, service: 7, startup: 6 } },
      { sno: 3, title: 'Best Time to Buy and Sell Stock II', difficulty: 'easy', leetcodeId: '122', category: 'greedy', description: 'Find maximum profit with unlimited transactions.', examples: [{ input: 'prices = [7,1,5,3,6,4]', output: '7' }], constraints: ['1 <= prices.length <= 3*10^4'], hints: ['Sum all positive differences', 'Buy and sell whenever profitable'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 7, service: 8, startup: 7 } },
      { sno: 4, title: 'Maximum Subarray', difficulty: 'easy', leetcodeId: '53', category: 'greedy', description: 'Find subarray with largest sum.', examples: [{ input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6' }], constraints: ['1 <= nums.length <= 10^5'], hints: ['Kadane\'s algorithm', 'Track current and max sum'], companies: ['Amazon', 'Facebook', 'Google', 'LinkedIn'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 5, title: 'Minimum Cost to Move Chips', difficulty: 'easy', leetcodeId: '1217', category: 'greedy', description: 'Move all chips to same position with minimum cost.', examples: [{ input: 'position = [1,2,3]', output: '1' }], constraints: ['1 <= position.length <= 100'], hints: ['Moving 2 positions is free', 'Count chips at odd and even positions'], companies: ['Google'], interviewFrequency: { faang: 5, service: 5, startup: 4 } },
      { sno: 6, title: 'Jump Game', difficulty: 'medium', leetcodeId: '55', category: 'greedy', description: 'Determine if you can reach last index.', examples: [{ input: 'nums = [2,3,1,1,4]', output: 'true' }], constraints: ['1 <= nums.length <= 10^4'], hints: ['Track furthest reachable index', 'Update as you iterate'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 7, title: 'Jump Game II', difficulty: 'medium', leetcodeId: '45', category: 'greedy', description: 'Return minimum number of jumps to reach last index.', examples: [{ input: 'nums = [2,3,1,1,4]', output: '2' }], constraints: ['1 <= nums.length <= 10^4'], hints: ['BFS/greedy approach', 'Track current and furthest reach'], companies: ['Amazon', 'Google', 'Facebook'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 8, title: 'Gas Station', difficulty: 'medium', leetcodeId: '134', category: 'greedy', description: 'Find starting gas station to complete circuit.', examples: [{ input: 'gas = [1,2,3,4,5], cost = [3,4,5,1,2]', output: '3' }], constraints: ['n == gas.length == cost.length'], hints: ['If total gas < total cost, impossible', 'Start after failed station'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 9, title: 'Non-overlapping Intervals', difficulty: 'medium', leetcodeId: '435', category: 'greedy', description: 'Remove minimum number of intervals to make rest non-overlapping.', examples: [{ input: 'intervals = [[1,2],[2,3],[3,4],[1,3]]', output: '1' }], constraints: ['1 <= intervals.length <= 10^5'], hints: ['Sort by end time', 'Greedy keep interval with earlier end'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 10, title: 'Minimum Number of Arrows to Burst Balloons', difficulty: 'medium', leetcodeId: '452', category: 'greedy', description: 'Find minimum arrows to burst all balloons.', examples: [{ input: 'points = [[10,16],[2,8],[1,6],[7,12]]', output: '2' }], constraints: ['1 <= points.length <= 10^5'], hints: ['Sort by end coordinate', 'Shoot at end, burst all overlapping'], companies: ['Facebook', 'Google'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 11, title: 'Task Scheduler', difficulty: 'medium', leetcodeId: '621', category: 'greedy', description: 'Return least number of units of time to finish all tasks with n cooling interval.', examples: [{ input: 'tasks = ["A","A","A","B","B","B"], n = 2', output: '8' }], constraints: ['1 <= task.length <= 10^4'], hints: ['Count task frequencies', 'Formula based on most frequent'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 12, title: 'Candy', difficulty: 'hard', leetcodeId: '135', category: 'greedy', description: 'Distribute candies to children with minimum total.', examples: [{ input: 'ratings = [1,0,2]', output: '5' }], constraints: ['n == ratings.length', '1 <= n <= 2*10^4'], hints: ['Two passes: left to right, right to left', 'Take max of two passes'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 13, title: 'Create Maximum Number', difficulty: 'hard', leetcodeId: '321', category: 'greedy', description: 'Return maximum number of length k from digits of two arrays.', examples: [{ input: 'nums1 = [3,4,6,5], nums2 = [9,1,2,5,8,3], k = 5', output: '[9,8,6,5,3]' }], constraints: ['1 <= nums1.length, nums2.length <= 500'], hints: ['Select from one array, rest from other', 'Merge greedily'], companies: ['Google'], interviewFrequency: { faang: 5, service: 4, startup: 3 } },
      { sno: 14, title: 'Patching Array', difficulty: 'hard', leetcodeId: '330', category: 'greedy', description: 'Return minimum number of patches required.', examples: [{ input: 'nums = [1,3], n = 6', output: '1' }], constraints: ['1 <= nums.length <= 1000'], hints: ['Track reachable range [1, miss)', 'If nums[i] <= miss, extend range'], companies: ['Google'], interviewFrequency: { faang: 5, service: 4, startup: 3 } },
      { sno: 15, title: 'IPO', difficulty: 'hard', leetcodeId: '502', category: 'greedy', description: 'Maximize initial capital after completing at most k projects.', examples: [{ input: 'k = 2, w = 0, profits = [1,2,3], capital = [0,1,1]', output: '4' }], constraints: ['1 <= k <= 10^5'], hints: ['Max heap for profits', 'Select affordable projects'], companies: ['Facebook'], interviewFrequency: { faang: 6, service: 5, startup: 4 } }
    ]
  },

  heaps: {
    name: 'Heaps (Priority Queue)',
    description: 'Master heap data structure for efficient access to extremes',
    recommendedDays: 1.5,
    problems: [
      { sno: 1, title: 'Kth Largest Element in Array', difficulty: 'easy', leetcodeId: '215', category: 'heap', description: 'Find kth largest element in unsorted array.', examples: [{ input: 'nums = [3,2,1,5,6,4], k = 2', output: '5' }], constraints: ['1 <= k <= nums.length <= 10^4'], hints: ['Min heap of size k', 'Max heap and pop k times'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 2, title: 'Last Stone Weight', difficulty: 'easy', leetcodeId: '1046', category: 'heap', description: 'Smash heaviest two stones until one or none left.', examples: [{ input: 'stones = [2,7,4,1,8,1]', output: '1' }], constraints: ['1 <= stones.length <= 30'], hints: ['Max heap', 'Take two largest, smash'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 6, service: 7, startup: 6 } },
      { sno: 3, title: 'Relative Ranks', difficulty: 'easy', leetcodeId: '506', category: 'heap', description: 'Assign relative ranks to scores.', examples: [{ input: 'score = [5,4,3,2,1]', output: '["Gold Medal","Silver Medal","Bronze Medal","4","5"]' }], constraints: ['1 <= score.length <= 10^4'], hints: ['Sort with indices', 'Or use heap'], companies: ['Google'], interviewFrequency: { faang: 5, service: 6, startup: 5 } },
      { sno: 4, title: 'Find K Pairs with Smallest Sums', difficulty: 'easy', leetcodeId: '373', category: 'heap', description: 'Find k pairs with smallest sums from two arrays.', examples: [{ input: 'nums1 = [1,7,11], nums2 = [2,4,6], k = 3', output: '[[1,2],[1,4],[1,6]]' }], constraints: ['1 <= nums1.length, nums2.length <= 10^5'], hints: ['Min heap of pairs', 'Start with first k from nums1'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 5, title: 'Kth Largest Element in Stream', difficulty: 'easy', leetcodeId: '703', category: 'heap', description: 'Design class to find kth largest element in stream.', examples: [{ input: 'k = 3, arr = [4,5,8,2], add(3), add(5)', output: '[4,5,5,8,8,8]' }], constraints: ['1 <= k <= 10^4'], hints: ['Min heap of size k', 'Maintain invariant'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 6, title: 'Top K Frequent Elements', difficulty: 'medium', leetcodeId: '347', category: 'heap', description: 'Return k most frequent elements.', examples: [{ input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1,2]' }], constraints: ['1 <= nums.length <= 10^5'], hints: ['Count frequencies', 'Min heap of size k by frequency'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 7, title: 'K Closest Points to Origin', difficulty: 'medium', leetcodeId: '973', category: 'heap', description: 'Return k closest points to origin.', examples: [{ input: 'points = [[1,3],[-2,2]], k = 1', output: '[[-2,2]]' }], constraints: ['1 <= k <= points.length <= 10^4'], hints: ['Max heap of size k', 'Or quickselect'], companies: ['Facebook', 'Amazon', 'Google'], interviewFrequency: { faang: 8, service: 8, startup: 7 } },
      { sno: 8, title: 'Reorganize String', difficulty: 'medium', leetcodeId: '767', category: 'heap', description: 'Rearrange string so no two adjacent characters are same.', examples: [{ input: 's = "aab"', output: '"aba"' }], constraints: ['1 <= s.length <= 500'], hints: ['Max heap by frequency', 'Place most frequent with gap'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 9, title: 'Meeting Rooms II', difficulty: 'medium', leetcodeId: '253', category: 'heap', description: 'Find minimum number of meeting rooms required.', examples: [{ input: 'intervals = [[0,30],[5,10],[15,20]]', output: '2' }], constraints: ['1 <= intervals.length <= 10^4'], hints: ['Sort by start time', 'Min heap of end times'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 10, title: 'Kth Smallest Element in Sorted Matrix', difficulty: 'medium', leetcodeId: '378', category: 'heap', description: 'Return kth smallest element in n x n matrix where each row and column is sorted.', examples: [{ input: 'matrix = [[1,5,9],[10,11,13],[12,13,15]], k = 8', output: '13' }], constraints: ['n == matrix.length'], hints: ['Min heap of first column', 'Binary search on value'], companies: ['Facebook', 'Amazon', 'Google'], interviewFrequency: { faang: 7, service: 7, startup: 6 } },
      { sno: 11, title: 'Find Median from Data Stream', difficulty: 'medium', leetcodeId: '295', category: 'heap', description: 'Find median of data stream.', examples: [{ input: 'addNum(1), addNum(2), findMedian()', output: '1.5' }], constraints: ['-10^5 <= num <= 10^5'], hints: ['Two heaps: max for lower half, min for upper', 'Balance heaps'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 12, title: 'Merge K Sorted Lists', difficulty: 'hard', leetcodeId: '23', category: 'heap', description: 'Merge k sorted linked lists.', examples: [{ input: 'lists = [[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]' }], constraints: ['k == lists.length', '0 <= k <= 10^4'], hints: ['Min heap of list heads', 'Pop smallest, push next'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 9, service: 9, startup: 8 } },
      { sno: 13, title: 'Smallest Range Covering K Lists', difficulty: 'hard', leetcodeId: '632', category: 'heap', description: 'Find smallest range that includes at least one number from each of k lists.', examples: [{ input: 'nums = [[4,10,15,24,26],[0,9,12,20],[5,18,22,30]]', output: '[20,24]' }], constraints: ['nums.length == k'], hints: ['Min heap tracking elements', 'Track min and max'], companies: ['Google'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 14, title: 'Find K-th Smallest Pair Distance', difficulty: 'hard', leetcodeId: '719', category: 'heap', description: 'Return kth smallest pair distance among all pairs.', examples: [{ input: 'nums = [1,3,1], k = 1', output: '0' }], constraints: ['n == nums.length', '1 <= n <= 10^4'], hints: ['Sort array', 'Binary search on distance'], companies: ['Google'], interviewFrequency: { faang: 5, service: 4, startup: 3 } },
      { sno: 15, title: 'Sliding Window Median', difficulty: 'hard', leetcodeId: '480', category: 'heap', description: 'Find median in sliding window.', examples: [{ input: 'nums = [1,3,-1,-3,5,3,6,7], k = 3', output: '[1.00000,-1.00000,-1.00000,3.00000,5.00000,6.00000]' }], constraints: ['1 <= k <= nums.length <= 10^5'], hints: ['Two heaps with delayed deletion', 'Lazy removal'], companies: ['Facebook', 'Google'], interviewFrequency: { faang: 6, service: 5, startup: 4 } }
    ]
  },

  tries: {
    name: 'Tries (Prefix Trees)',
    description: 'Master trie data structure for string problems',
    recommendedDays: 1.5,
    problems: [
      { sno: 1, title: 'Implement Trie (Prefix Tree)', difficulty: 'easy', leetcodeId: '208', category: 'tries', description: 'Implement a trie with insert, search, and startsWith methods.', examples: [{ input: '["Trie","insert","search","search","startsWith","insert","search"]', output: '[null,null,false,true,null,true]' }], constraints: ['1 <= word.length, prefix.length <= 2000'], hints: ['Node contains children map', 'isEnd flag for word end'], companies: ['Amazon', 'Facebook', 'Google', 'Microsoft'], interviewFrequency: { faang: 9, service: 8, startup: 7 } },
      { sno: 2, title: 'Longest Common Prefix', difficulty: 'easy', leetcodeId: '14', category: 'tries', description: 'Find longest common prefix string amongst array of strings.', examples: [{ input: 'strs = ["flower","flow","flight"]', output: '"fl"' }], constraints: ['1 <= strs.length <= 200'], hints: ['Horizontal scanning', 'Or build trie'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 7, service: 8, startup: 6 } },
      { sno: 3, title: 'Design Add and Search Words Data Structure', difficulty: 'easy', leetcodeId: '211', category: 'tries', description: 'Search word with support for . as wildcard.', examples: [{ input: '["WordDictionary","addWord","addWord","search","search"]', output: '[null,null,null,false,true]' }], constraints: ['1 <= word.length <= 500'], hints: ['Trie with DFS for .', 'Handle wildcards recursively'], companies: ['Facebook', 'Amazon'], interviewFrequency: { faang: 8, service: 7, startup: 6 } },
      { sno: 4, title: 'Replace Words', difficulty: 'easy', leetcodeId: '648', category: 'tries', description: 'Replace successors in sentence with root forming it.', examples: [{ input: 'dictionary = ["cat","bat","rat"], sentence = "the cattle was rattled by the battery"', output: '"the cat was rat by the bat"' }], constraints: ['1 <= dictionary.length <= 1000'], hints: ['Build trie from dictionary', 'Find shortest root for each word'], companies: ['Amazon'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 5, title: 'Map Sum Pairs', difficulty: 'easy', leetcodeId: '677', category: 'tries', description: 'Implement MapSum class with insert and sum operations.', examples: [{ input: '["MapSum","insert","sum","insert","sum"]', output: '[null,null,3,null,5]' }], constraints: ['1 <= key.length, prefix.length <= 50'], hints: ['Trie with value at each node', 'Sum includes all words with prefix'], companies: ['Amazon'], interviewFrequency: { faang: 6, service: 6, startup: 5 } },
      { sno: 6, title: 'Search Suggestions System', difficulty: 'medium', leetcodeId: '1268', category: 'tries', description: 'Return suggested products after each character of searchWord is typed.', examples: [{ input: 'products = ["mobile","mouse","moneypot","monitor","mousepad"], searchWord = "mouse"', output: '[["mobile","moneypot","monitor"],["mobile","moneypot","monitor"],["mouse","mousepad"],["mouse","mousepad"],["mouse","mousepad"]]' }], constraints: ['1 <= products.length <= 1000'], hints: ['Sort products', 'Or build trie with top 3 at each node'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 8, service: 7, startup: 6 } },
      { sno: 7, title: 'Design Search Autocomplete System', difficulty: 'medium', leetcodeId: '642', category: 'tries', description: 'Design search autocomplete system with historical data.', examples: [{ input: '["AutocompleteSystem","input","input","input","input"]', output: '[null,["i love you","island"],["i love you","island"],["i love you","island","i miss you"],["i love you","ironman","i miss you"]]' }], constraints: ['The number of nodes in the trie is in the range [1, 10000]'], hints: ['Trie with frequency count', 'Min heap for top 3'], companies: ['Amazon', 'Facebook'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 8, title: 'Implement Magic Dictionary', difficulty: 'medium', leetcodeId: '676', category: 'tries', description: 'Build dictionary with search method that allows exactly one character difference.', examples: [{ input: '["MagicDictionary", "buildDict", "search", "search", "search", "search"]', output: '[null, null, false, true, false, false]' }], constraints: ['1 <= dictionary.length <= 100'], hints: ['Build trie', 'Search with one change allowed'], companies: ['Amazon'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 9, title: 'Word Search II', difficulty: 'medium', leetcodeId: '212', category: 'tries', description: 'Find all words from words in board.', examples: [{ input: 'board = [["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]], words = ["oath","pea","eat","rain"]', output: '["eat","oath"]' }], constraints: ['m == board.length', 'n == board[i].length'], hints: ['Build trie from words', 'DFS from each cell'], companies: ['Amazon', 'Facebook', 'Google'], interviewFrequency: { faang: 8, service: 7, startup: 6 } },
      { sno: 10, title: 'Concatenated Words', difficulty: 'medium', leetcodeId: '472', category: 'tries', description: 'Return all concatenated words in given list.', examples: [{ input: 'words = ["cat","cats","catsdogcats","dog","dogcatsdog","hippopotamuses","rat","ratcatdogcat"]', output: '["catsdogcats","dogcatsdog","ratcatdogcat"]' }], constraints: ['1 <= words.length <= 10^4'], hints: ['Build trie', 'DFS with memoization'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 11, title: 'Maximum XOR of Two Numbers', difficulty: 'medium', leetcodeId: '421', category: 'tries', description: 'Find maximum XOR of two numbers in array.', examples: [{ input: 'nums = [3,10,5,25,2,8]', output: '28' }], constraints: ['1 <= nums.length <= 2*10^5'], hints: ['Build binary trie', 'For each number, find best XOR partner'], companies: ['Amazon', 'Google'], interviewFrequency: { faang: 7, service: 6, startup: 5 } },
      { sno: 12, title: 'Palindrome Pairs', difficulty: 'hard', leetcodeId: '336', category: 'tries', description: 'Find all pairs of distinct indices such that concatenation is palindrome.', examples: [{ input: 'words = ["bat","tab","cat"]', output: '[[0,1],[1,0]]' }], constraints: ['1 <= words.length <= 5000'], hints: ['Build trie of reversed words', 'Check palindrome suffix/prefix'], companies: ['Airbnb', 'Facebook'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 13, title: 'Stream of Characters', difficulty: 'hard', leetcodeId: '1032', category: 'tries', description: 'Design stream checker that returns true if suffix forms word.', examples: [{ input: '["StreamChecker","query","query","query","query"]', output: '[null,false,true,true,true]' }], constraints: ['1 <= words.length <= 2000'], hints: ['Build reversed trie', 'Query by building suffix'], companies: ['Amazon'], interviewFrequency: { faang: 6, service: 5, startup: 4 } },
      { sno: 14, title: 'Word Squares', difficulty: 'hard', leetcodeId: '425', category: 'tries', description: 'Given set of words, find all word squares.', examples: [{ input: 'words = ["area","lead","wall","lady","ball"]', output: '[["ball","area","lead","lady"],["wall","area","lead","lady"]]' }], constraints: ['1 <= words.length <= 1000'], hints: ['Build trie with prefix search', 'Backtrack by prefix'], companies: ['Google'], interviewFrequency: { faang: 5, service: 4, startup: 3 } },
      { sno: 15, title: 'Prefix and Suffix Search', difficulty: 'hard', leetcodeId: '745', category: 'tries', description: 'Design word filter with prefix and suffix search.', examples: [{ input: '["WordFilter","f"]', output: '[null,0]' }], constraints: ['1 <= words.length <= 15000'], hints: ['Build trie with suffix#word', 'Or store all suffix#prefix'], companies: ['Google'], interviewFrequency: { faang: 6, service: 5, startup: 4 } }
    ]
  }
};

// Flatten all problems into array for database seeding
function getAllProblems() {
  const allProblems = [];
  Object.values(comprehensiveProblemSet).forEach(topic => {
    topic.problems.forEach(problem => {
      allProblems.push({
        ...problem,
        topicName: topic.name,
        topicDescription: topic.description,
        recommendedDays: topic.recommendedDays,
        leetcodeUrl: problem.leetcodeId ? `https://leetcode.com/problems/${problem.title.toLowerCase().replace(/\s+/g, '-')}/` : null
      });
    });
  });
  return allProblems;
}

// Get problems by topic
function getProblemsByTopic(topicKey) {
  return comprehensiveProblemSet[topicKey]?.problems || [];
}

// Get topics info
function getTopicsInfo() {
  return Object.entries(comprehensiveProblemSet).map(([key, topic]) => ({
    key,
    name: topic.name,
    description: topic.description,
    problemCount: topic.problems.length,
    recommendedDays: topic.recommendedDays
  }));
}

// Get problems by difficulty
function getProblemsByDifficulty(difficulty) {
  return getAllProblems().filter(p => p.difficulty === difficulty);
}

// Get problems suitable for user's level based on resume
function getProblemsForUserLevel(userLevel, weakAreas = []) {
  let targetDifficulty;
  if (userLevel === 'Beginner') {
    targetDifficulty = ['easy'];
  } else if (userLevel === 'Intermediate') {
    targetDifficulty = ['easy', 'medium'];
  } else {
    targetDifficulty = ['medium', 'hard'];
  }
  
  // Map weak areas to topics
  const topicMapping = {
    'recursion': ['recursion'],
    'hash': ['hashing'],
    'hashing': ['hashing'],
    'two pointers': ['twoPointers'],
    'backtrack': ['backtracking'],
    'backtracking': ['backtracking'],
    'dp': ['dynamicProgramming'],
    'dynamic programming': ['dynamicProgramming'],
    'greedy': ['greedy'],
    'heap': ['heaps'],
    'priority queue': ['heaps'],
    'trie': ['tries'],
    'tree': ['trees'],
    'graph': ['graphs'],
    'linked list': ['linked_list']
  };
  
  // Find target topics from weak areas
  let targetTopics = [];
  weakAreas.forEach(area => {
    const areaLower = area.toLowerCase();
    Object.entries(topicMapping).forEach(([keyword, topics]) => {
      if (areaLower.includes(keyword)) {
        targetTopics.push(...topics);
      }
    });
  });
  
  // Get problems from target topics
  let recommendedProblems = [];
  if (targetTopics.length > 0) {
    targetTopics.forEach(topicKey => {
      const topicProblems = getProblemsByTopic(topicKey)
        .filter(p => targetDifficulty.includes(p.difficulty))
        .slice(0, 5);
      recommendedProblems.push(...topicProblems);
    });
  }
  
  // If no specific recommendations, return general problems
  if (recommendedProblems.length === 0) {
    recommendedProblems = getAllProblems()
      .filter(p => targetDifficulty.includes(p.difficulty))
      .slice(0, 10);
  }
  
  return recommendedProblems;
}

module.exports = {
  comprehensiveProblemSet,
  getAllProblems,
  getProblemsByTopic,
  getTopicsInfo,
  getProblemsByDifficulty,
  getProblemsForUserLevel
};
